name: updateWeb

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    # comment
    name: "Auto Update Statistics Data"
    # comment
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v4
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install packages
        run: "pip install --upgrade pip && pip install -r ./requirements.txt"
  
      - name: Update Data
        run: |
          sh run_all.sh

      - name: Commit report
        env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            GOOGLE_TOKEN: ${{ secrets.GOOGLE_FORM_KEYS }}
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} > ./google_form_keys.json
          git config --global user.name 'iamnotyourspy'
          git config --global user.email 'iamnotyourspy@gmail.com'
          git remote set-url origin https://iamnotyourspy:${{ secrets.ACCESS_TOKEN }}@github.com/iamnotyourspy/iamnotyourspy.github.io
          # git checkout -b main
          # git branch
          git add ./index.md
          git commit -m "github workflows auto update data"
          git push origin main

